export const puns = [
    "I used to play piano by ear, but now I use my hands.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I told my computer I needed a break, and now it won't stop laughing at me.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why was the math book sad? Because it had too many problems!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What do you call a fish with no eyes? Fsh.",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "I would tell you a joke about construction, but I'm still working on it.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "I would tell you a joke about construction, but I'm still working on it.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What do you call a factory that makes okay products? A satisfactory.",
  "I used to play piano by ear, but now I use my hands.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I told my computer I needed a break, and now it won't stop laughing at me.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why was the math book sad? Because it had too many problems!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What do you call a fish with no eyes? Fsh.",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "I would tell you a joke about construction, but I'm still working on it.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What do you get when you cross a snowman and a vampire? Frostbite!",
  "I would tell you a joke about construction, but I'm still working on it.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What do you call a factory that makes okay products? A satisfactory.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What do you call a factory that makes okay products? A satisfactory.",
  "I used to play piano by ear, but now I use my hands.",
  "I'm friends with all gardeners because they have a lot of plant knowledge.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What's a skeleton's least favorite room in the house? The living room!",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I'm friends with all gardeners because they have a lot of plant knowledge.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What's a skeleton's least favorite room in the house? The living room!",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I'm friends with all gardeners because they have a lot of plant knowledge.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What's a skeleton's least favorite room in the house? The living room!",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What's a skeleton's least favorite room in the house? The living room!",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I'm friends with all gardeners because they have a lot of plant knowledge.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What's a skeleton's least favorite room in the house? The living room!",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I'm friends with all gardeners because they have a lot of plant knowledge.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "What's a skeleton's least favorite room in the house? The living room!",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I'm friends with all electricians. We have such good current connections.",
  "I don't trust stairs because they're always up to something.",
  "Why don't some couples go to the gym? Because some relationships don't work out!"
]

export const getPun = () => {
    return puns[Math.floor(Math.random() * puns.length)];
}